### ISSUE TITLE
No module named 'autopy'

### ISSUE THREAD

**Issue by esiquiel** [FalconDigital/MexawTurbo-Swap#1]
When I run the script with python it gives me this message:
`No module named 'autopy'`
And it keeps me running without doing anything

Any solution?

**Comment by iiONE** [comment]
pip install autopy

**Comment by iiONE** [comment]
> When I run the script with python it gives me this message:
> `No module named 'autopy'`
> And it keeps me running without doing anything
> 
> Any solution?

pip install autopy

**Comment by lofiy** [comment]
hi where is this turbo
